[package]
name = "realsense-capture-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.9"
rocket = "0.5.0"
serde = "1.0.197"
serde_yaml = "0.9.32"
